// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906115420_InitialErp")]
    partial class InitialErp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Department_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Department_Address");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Department_Name");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Name", "LEN(LTRIM(RTRIM([Department_Name]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentAddress = "Head Office",
                            DepartmentName = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentAddress = "Head Office",
                            DepartmentName = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentAddress = "Head Office",
                            DepartmentName = "Accounting & Finance"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentAddress = "Factory Building A",
                            DepartmentName = "Production"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentAddress = "Factory Building B",
                            DepartmentName = "Quality Assurance"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentAddress = "Warehouse Zone A",
                            DepartmentName = "Warehouse"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentAddress = "Head Office",
                            DepartmentName = "Procurement"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentAddress = "Head Office",
                            DepartmentName = "Sales & Export"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly>("DateJoined")
                        .HasColumnType("date")
                        .HasColumnName("Date_Joined");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_Birth");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_ID");

                    b.Property<string>("EmployeeAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Employee_Address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Employee_First_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Employee_Last_Name");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employees_Dates", "[Date_of_Birth] > '0001-01-01' AND [Date_Joined] > [Date_of_Birth] AND [Date_Joined] <= CONVERT(date, GETDATE())");

                            t.HasCheckConstraint("CK_Employees_FirstName", "LEN(LTRIM(RTRIM([Employee_First_name]))) > 0");

                            t.HasCheckConstraint("CK_Employees_Gender", "[Gender] IN ('Male', 'Female', 'Other', 'Prefer not to say')");

                            t.HasCheckConstraint("CK_Employees_LastName", "LEN(LTRIM(RTRIM([Employee_Last_Name]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateJoined = new DateOnly(2024, 1, 15),
                            DateOfBirth = new DateOnly(1990, 1, 10),
                            DepartmentId = 1,
                            EmployeeAddress = "Demo address 1, Bangkok",
                            FirstName = "Somchai",
                            Gender = "Male",
                            LastName = "Jaidee"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateJoined = new DateOnly(2024, 2, 15),
                            DateOfBirth = new DateOnly(1991, 2, 10),
                            DepartmentId = 4,
                            EmployeeAddress = "Demo address 2, Bangkok",
                            FirstName = "Anan",
                            Gender = "Male",
                            LastName = "Chaisuk"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateJoined = new DateOnly(2024, 3, 15),
                            DateOfBirth = new DateOnly(1992, 3, 10),
                            DepartmentId = 2,
                            EmployeeAddress = "Demo address 3, Bangkok",
                            FirstName = "Nattaya",
                            Gender = "Female",
                            LastName = "Deeprasert"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateJoined = new DateOnly(2024, 4, 15),
                            DateOfBirth = new DateOnly(1993, 4, 10),
                            DepartmentId = 3,
                            EmployeeAddress = "Demo address 4, Bangkok",
                            FirstName = "Pimchanok",
                            Gender = "Female",
                            LastName = "Kanjana"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateJoined = new DateOnly(2024, 5, 15),
                            DateOfBirth = new DateOnly(1994, 5, 10),
                            DepartmentId = 6,
                            EmployeeAddress = "Demo address 5, Bangkok",
                            FirstName = "Kittipong",
                            Gender = "Male",
                            LastName = "Arun"
                        },
                        new
                        {
                            EmployeeId = 6,
                            DateJoined = new DateOnly(2024, 6, 15),
                            DateOfBirth = new DateOnly(1995, 6, 10),
                            DepartmentId = 5,
                            EmployeeAddress = "Demo address 6, Bangkok",
                            FirstName = "Sudarat",
                            Gender = "Female",
                            LastName = "Meechai"
                        },
                        new
                        {
                            EmployeeId = 7,
                            DateJoined = new DateOnly(2024, 7, 15),
                            DateOfBirth = new DateOnly(1996, 7, 10),
                            DepartmentId = 7,
                            EmployeeAddress = "Demo address 7, Bangkok",
                            FirstName = "Thanawat",
                            Gender = "Male",
                            LastName = "Wongsa"
                        },
                        new
                        {
                            EmployeeId = 8,
                            DateJoined = new DateOnly(2024, 8, 15),
                            DateOfBirth = new DateOnly(1997, 8, 10),
                            DepartmentId = 8,
                            EmployeeAddress = "Demo address 8, Bangkok",
                            FirstName = "Jirawat",
                            Gender = "Male",
                            LastName = "Intara"
                        },
                        new
                        {
                            EmployeeId = 9,
                            DateJoined = new DateOnly(2024, 9, 15),
                            DateOfBirth = new DateOnly(1998, 9, 10),
                            DepartmentId = 4,
                            EmployeeAddress = "Demo address 9, Bangkok",
                            FirstName = "Waranya",
                            Gender = "Female",
                            LastName = "Saelim"
                        },
                        new
                        {
                            EmployeeId = 10,
                            DateJoined = new DateOnly(2024, 10, 15),
                            DateOfBirth = new DateOnly(1999, 10, 10),
                            DepartmentId = 1,
                            EmployeeAddress = "Demo address 10, Bangkok",
                            FirstName = "Pattarapong",
                            Gender = "Male",
                            LastName = "Bunmee"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
